# Generated by Django 4.2 on 2024-11-19 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_make', models.CharField(choices=[('Toyota', 'Toyota'), ('Honda', 'Honda'), ('Volvo', 'Volvo'), ('BMW', 'BMW'), ('Mazda', 'Mazda'), ('Ford', 'Ford'), ('Subaru', 'Subaru'), ('Nissan', 'Nissan'), ('Suzuki', 'Suzuki'), ('Audi', 'Audi')], max_length=50)),
                ('car_model', models.CharField(max_length=50)),
                ('automation', models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], max_length=10)),
                ('year', models.PositiveIntegerField()),
            ],
        ),
    ]
