# Generated by Django 4.2 on 2024-11-22 18:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('royaladmin', '0001_initial'),
        ('carapp', '0003_newsletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carbooking',
            name='automation',
        ),
        migrations.RemoveField(
            model_name='carbooking',
            name='car_make',
        ),
        migrations.RemoveField(
            model_name='carbooking',
            name='car_model',
        ),
        migrations.RemoveField(
            model_name='carbooking',
            name='year',
        ),
        migrations.AddField(
            model_name='carbooking',
            name='car',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='royaladmin.car'),
        ),
        migrations.AddField(
            model_name='carbooking',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='carbooking',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='carbooking',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carbooking',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='carbooking',
            name='phone_number',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='carbooking',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='carbooking',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
