# Generated by Django 4.2 on 2024-11-25 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('royaladmin', '0001_initial'),
        ('carapp', '0005_ridehailing'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('id_number', models.CharField(max_length=20)),
                ('kra_pin', models.CharField(max_length=20)),
                ('road_test_date', models.DateField()),
                ('road_test_confirmed', models.BooleanField(default=False)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='royaladmin.car')),
            ],
        ),
    ]
