# Generated by Django 4.2 on 2024-11-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0006_carpurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbooking',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='carbooking',
            name='transaction_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
