# Generated by Django 4.2 on 2024-11-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royaladmin', '0002_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='facebook_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='linkedin_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='twitter_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
